---
title: "Research projects"
---

Recent projects:

## Synaptic connectivity

> **A study of synaptic connectivity in healthy volunteers and patients diagnosed with mental disorders**

Synaptic pathology has been suggested in the aetiology of schizophrenia and a number of incidental findings support the role of abnormalities in synaptic pathology in behavioural and cognitive impairments. Pre-synaptic markers help relate changes in synaptic density and a number of alterations in presynaptic markers such as presynaptic synaptic protein 2A (SV2A) by allowing us to indirectly measure synaptic density *in vivo* using [11C]UCB-J - a selective radiotracer that binds to SV2A.

SV2A was identified as the site of action of several second-generation antiepileptic drugs including levetiracetam (LEV), which acts by reducing presynaptic neurotransmitter (especially glutamate) release in brain neurons, and it has been shown that their antiepileptic efficacy correlates with their binding affinity to SV2A. Given that SV2A levels have been shown to be altered in schizophrenia, SV2A’s regional physiological role as a modulator of neurotransmitter release is important for understanding altered neurotransmitter release seen in schizophrenia. By pharmacologically challenging SV2A using a single dose of LEV and recording functional changes with fMRI and MEG, we will be able to address the hypothesis whether functional dysconnectivity in psychotic disorders is related to synaptic loss or impaired synaptic transmission.

<button type="button" class="btn btn-light btn-sm"><a href="https://bepartofresearch.nihr.ac.uk/trial-details/trial-detail?trialId=50590&location=London,%20UK&distance=" terget="_blank">
Be part of research</a></button>
<button type="button" class="btn btn-light btn-sm"><a href="https://sense.odp.nihr.ac.uk/public/single/?appid=27f93da6-3ea4-404a-afce-24cfe1c613c8&obj=601a080e-5f30-4813-9ab1-14213b816f85&theme=nihr%20theme&opt=nointeraction,noselections&select=$::StudyID,61077&identity=preview" target="_blank">NIHR</a></button>
<button type="button" class="btn btn-light btn-sm"><a href="https://www.hra.nhs.uk/planning-and-improving-research/application-summaries/research-summaries/synaptic-connectivity/" target="_blank">HRA</a></button>
<button type="button" class="btn btn-light btn-sm"><a href="mailto:synaptic-connectivity@kcl.ac.uk" target="_blank">E-mail</a></button>

## Synaptic and neural function
> **A study of synaptic markers and their relationship to neural function in healthy volunteers and patients diagnosed with mental disorders**

*to add description*

<button type="button" class="btn btn-light btn-sm"><a href="https://bepartofresearch.nihr.ac.uk/trial-details/trial-detail?trialId=19375&location=&distance=" terget="_blank">
Be part of research</a></button>
<button type="button" class="btn btn-light btn-sm"><a href="https://www.hra.nhs.uk/planning-and-improving-research/application-summaries/research-summaries/synaptic-and-neural-function/" target="_blank">HRA</a></button>

## RESTORE

*to add description*

<button type="button" class="btn btn-light btn-sm"><a href="https://bepartofresearch.nihr.ac.uk/trial-details/trial-detail?trialId=25337&location=&distance=" terget="_blank">
Be part of research</a></button>
